/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FruitType = IDL.Variant({
  'grapes' : IDL.Null,
  'apple' : IDL.Null,
  'orange' : IDL.Null,
  'pear' : IDL.Null,
  'plum' : IDL.Null,
  'banana' : IDL.Null,
  'strawberry' : IDL.Null,
  'peach' : IDL.Null,
});
export const ResultEntry = IDL.Record({
  'fruit' : FruitType,
  'freshnessConfidence' : IDL.Nat,
  'freshnessScore' : IDL.Nat,
  'timestamp' : IDL.Int,
  'confidence' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(ResultEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAnalysisResult' : IDL.Func(
      [FruitType, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FruitType = IDL.Variant({
    'grapes' : IDL.Null,
    'apple' : IDL.Null,
    'orange' : IDL.Null,
    'pear' : IDL.Null,
    'plum' : IDL.Null,
    'banana' : IDL.Null,
    'strawberry' : IDL.Null,
    'peach' : IDL.Null,
  });
  const ResultEntry = IDL.Record({
    'fruit' : FruitType,
    'freshnessConfidence' : IDL.Nat,
    'freshnessScore' : IDL.Nat,
    'timestamp' : IDL.Int,
    'confidence' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(ResultEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAnalysisResult' : IDL.Func(
        [FruitType, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };