/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type FruitType = { 'grapes' : null } |
  { 'apple' : null } |
  { 'orange' : null } |
  { 'pear' : null } |
  { 'plum' : null } |
  { 'banana' : null } |
  { 'strawberry' : null } |
  { 'peach' : null };
export interface ResultEntry {
  'fruit' : FruitType,
  'freshnessConfidence' : bigint,
  'freshnessScore' : bigint,
  'timestamp' : bigint,
  'confidence' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHistory' : ActorMethod<[], Array<ResultEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAnalysisResult' : ActorMethod<
    [FruitType, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];